//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InventoryControlCarts = new HashSet<InventoryControlCart>();
            this.InvoiceInventoryTypes = new HashSet<InvoiceInventoryType>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int StaffId { get; set; }
        public int InvoiceTypeJournalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryControlCart> InventoryControlCarts { get; set; }
        public virtual InvoiceTypeJournal InvoiceTypeJournal { get; set; }
        public virtual StaffJournal StaffJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceInventoryType> InvoiceInventoryTypes { get; set; }
    }
}
