//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnterpriseStocksEntities : DbContext
    {
        public EnterpriseStocksEntities()
            : base("name=EnterpriseStocksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InventoryControlCart> InventoryControlCarts { get; set; }
        public virtual DbSet<InventoryTypeJournal> InventoryTypeJournals { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceInventoryType> InvoiceInventoryTypes { get; set; }
        public virtual DbSet<InvoiceTypeJournal> InvoiceTypeJournals { get; set; }
        public virtual DbSet<StaffJournal> StaffJournals { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockInventoryType> StockInventoryTypes { get; set; }
    }
}
